name: Build Nexortex OS
on:
  workflow_dispatch: # Позволява ти да пускаш сглобяването ръчно с един бутон

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          prune: true
