name: Build Nexortex OS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Nexortex ISO
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          registry_token: ${{ github.token }}
